
POST  http://localhost:4000/products/create 
Content-Type: application/json

{
    "name": "hockey",
    "quantity": 5
}

###
GET http://localhost:4000/products


###
DELETE http://localhost:4000/products/634ad58d0708bf541be66423


###
POST http://localhost:4000/products/634ac23e87d511847872627e/updateQuantity/10